"""L3 Mode A benchmark configuration — this file IS the design.

Edit, then:  uv run python -m dlc.l3bench.run --dry-run
IRB: results go OUTSIDE the repo (OUT_DIR); student circuits are read
from the local archive and NEVER copied into the repo.
"""

import os
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent

# ---------------------------------------------------------------- paths
OUT_DIR = Path(os.environ.get(
    "DLC_BENCH_OUT", r"C:\Users\69450\projects\dlc_benchmark_out"))
ARCHIVE = Path(os.environ.get(
    "DLC_BENCH_ARCHIVE",
    r"C:\Users\69450\projects\Archived UNC COMP 311 Spring DATA"))
# The official control-unit ANSWER file — base for all destroy variants.
DESTROY_BASE = Path(os.environ.get(
    "DLC_BENCH_DESTROY", r"C:\Users\69450\Downloads\tmmp\control-unit.dig"))
PREPARED = OUT_DIR / "prepared"     # generated destroy variants land here
RAW_DIR = OUT_DIR / "raw"           # full per-run debug results (audit)

# --------------------------------------------------------------- models
MODELS_FULL = ["claude-sonnet-4-6", "claude-sonnet-5", "claude-opus-5"]
MODELS_PROBE = ["claude-haiku-4-5-20251001", "gpt-5"]
ROUNDS = 3

# $/M input, $/M output. sonnet-5 = intro pricing through 2026-08-31
# (3.00/15.00 after). gpt-5 = ASSUMED — verify on the OpenAI pricing
# page before the run; the hard caps below protect the wallet either way.
PRICES = {
    "claude-sonnet-4-6":         (3.00, 15.00),
    "claude-sonnet-5":           (2.00, 10.00),
    "claude-opus-5":             (5.00, 25.00),
    "claude-haiku-4-5-20251001": (1.00, 5.00),
    "gpt-5":                     (1.25, 10.00),
}

TOTAL_CAP_USD = 55.0   # hard stop for the whole run
GPT_CAP_USD = 8.0      # hard stop for gpt-5 alone (owner wants < $10)

# ------------------------------------------------------------- circuits
# kind: "llm" rows call the model; "control" rows must make ZERO calls
# (their expected deterministic mode is asserted instead).
# probe=True rows are the subset the PROBE models run.
_B = REPO / "data/sample_circuits/30_bug_benchmark"
_T3 = REPO / "data/sample_circuits/tier3_realistic"

CIRCUITS = [
    # --- repo fixtures (synthetic, committed, lab 1-3 tier) ---
    dict(id="bug1_mux_in3", path=_B / "bug1_meaningless_mux_in3/tier3_calculator.dig",
         kind="llm", bugs="L03", probe=False),
    dict(id="bug2_floating_out", path=_B / "bug2_wrong_floating_pipeline_output/Wrong_floating_pipeline_output.dig",
         kind="llm", bugs="L04", probe=False),
    dict(id="bug3_wrong_cin", path=_B / "bug3_wrong_cin/Wrong_cin.dig",
         kind="llm", bugs="L09", probe=True),
    dict(id="bug5_bool_led", path=_B / "bug5_wrong_boolean_gate_decoder_logic/wrong_bool_LED1.dig",
         kind="llm", bugs="L02", probe=True),
    dict(id="bug6_hidden_mux", path=_B / "bug6_hidden_mux_case3/uncovered_op_calculator.dig",
         kind="llm", bugs="L03", probe=True),
    dict(id="bug8_gapped_led", path=_B / "bug8_gapped_led_minterm/gapped_LED1.dig",
         kind="llm", bugs="L02,L09", probe=False),
    # --- destroy variants (generated by prepare.py from DESTROY_BASE;
    #     filename stays control-unit.dig so production rules apply) ---
    dict(id="cu_emptyrom", path=PREPARED / "cu_emptyrom" / "control-unit.dig",
         kind="llm", bugs="L01,P01", probe=True),
    dict(id="cu_1gate", path=PREPARED / "cu_1gate" / "control-unit.dig",
         kind="llm", bugs="L11", probe=True),
    dict(id="cu_2gates", path=PREPARED / "cu_2gates" / "control-unit.dig",
         kind="llm", bugs="L11", probe=False),
    dict(id="cu_3gates", path=PREPARED / "cu_3gates" / "control-unit.dig",
         kind="llm", bugs="L11", probe=True),
    # --- real student rows (archive paths, local-only) ---
    dict(id="s009_cpu_wrong_rom",
         path=ARCHIVE / r"Submissions\Lab5\001\009\Apr-28-12AM\lab5\cpu.dig",
         kind="llm", bugs="L01", probe=False),
    # --- zero-call controls ---
    dict(id="bug4_missing_pipeline", path=_B / "bug4_missing_pipeline/Missing_pipeline.dig",
         kind="control", bugs="L10", expect="lazy"),
    dict(id="bug7_broken_child", path=_B / "bug7_broken_child/tier3_calculator.dig",
         kind="control", bugs="S-child", expect="child_gate"),
    dict(id="s008_cu_raw_names",
         path=ARCHIVE / r"Submissions\Lab5\001\008\Apr-26-11PM\lab5\control-unit.dig",
         kind="control", bugs="P03", expect="refusal"),
    dict(id="s018_cpu_starter",
         path=ARCHIVE / r"Submissions\Lab5\001\018\Apr-27-6PM\lab5\cpu.dig",
         kind="control", bugs="P04", expect="quiet"),
    dict(id="cu_clean", path=PREPARED / "cu_clean" / "control-unit.dig",
         kind="control", bugs="NONE", expect="clear"),
    dict(id="adder_clean", path=_T3 / "pipelined_adder_correct.dig",
         kind="control", bugs="NONE", expect="clear"),
]

# Rough token profile per circuit class, for the dry-run estimate only
# (input/call, output/call by model family, calls/run) — from measured
# r42 runs. The live run bills from real usage, not from this.
EST_SMALL = dict(in_call=7_000, calls=2.0)
EST_CU = dict(in_call=22_000, calls=2.5)
EST_CPU = dict(in_call=35_000, calls=2.5)
EST_OUT_CALL = {
    "claude-sonnet-4-6": 1_500, "claude-sonnet-5": 2_500,
    "claude-opus-5": 3_000, "claude-haiku-4-5-20251001": 1_000,
    "gpt-5": 4_000,
}


def circuit_class(cid: str) -> dict:
    if cid.startswith(("cu_", "s008_cu")):
        return EST_CU
    if "cpu" in cid:
        return EST_CPU
    return EST_SMALL
